# Generated by Django 4.2.1 on 2024-05-15 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сложности')),
            ],
            options={
                'verbose_name': 'Сложности',
                'verbose_name_plural': 'Сложности',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название маршрута')),
                ('duration', models.TimeField(verbose_name='Длительность')),
                ('length', models.FloatField(max_length=6, verbose_name='Протяженность')),
                ('complexity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='excursions.complexity', verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Маршруты',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название экскурсии')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('small_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('photo', models.CharField(verbose_name='Фото')),
                ('datee', models.DateField(verbose_name='Дата проведения')),
                ('timee', models.TimeField(verbose_name='Время')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('group_size', models.IntegerField(verbose_name='Размер группы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursions.category', verbose_name='Категория')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гид')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Экскурсии',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_reserve', models.IntegerField(verbose_name='Количество бронируемых мест')),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
