# Generated by Django 4.2.1 on 2024-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('small_description', models.TextField(max_length=200)),
                ('photo', models.CharField()),
                ('datee', models.DateField()),
                ('timee', models.TimeField()),
                ('guide_id', models.IntegerField()),
                ('cost', models.FloatField()),
                ('category', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('group_size', models.IntegerField()),
            ],
        ),
    ]
