# Generated by Django 4.2.1 on 2024-04-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [

    ]
