# Generated by Django 4.2.1 on 2024-04-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_excursions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='route_id',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.TimeField()),
                ('length', models.FloatField(max_length=6)),
                ('complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='excursions.complexity')),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='excursions.route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursions.category'),
        ),
    ]
